// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: akrostolion/labeler.proto

package akrostolion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LabelerService_LabelStream_FullMethodName = "/akrostolion.LabelerService/LabelStream"
	LabelerService_Label_FullMethodName       = "/akrostolion.LabelerService/Label"
)

// LabelerServiceClient is the client API for LabelerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LabelerService stamps Kubernetes manifests with platform labels.
type LabelerServiceClient interface {
	LabelStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LabelStreamRequest, LabelStreamResponse], error)
	Label(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LabelRequest, LabelResponse], error)
}

type labelerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLabelerServiceClient(cc grpc.ClientConnInterface) LabelerServiceClient {
	return &labelerServiceClient{cc}
}

func (c *labelerServiceClient) LabelStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LabelStreamRequest, LabelStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LabelerService_ServiceDesc.Streams[0], LabelerService_LabelStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LabelStreamRequest, LabelStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelerService_LabelStreamClient = grpc.BidiStreamingClient[LabelStreamRequest, LabelStreamResponse]

func (c *labelerServiceClient) Label(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LabelRequest, LabelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LabelerService_ServiceDesc.Streams[1], LabelerService_Label_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LabelRequest, LabelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelerService_LabelClient = grpc.ClientStreamingClient[LabelRequest, LabelResponse]

// LabelerServiceServer is the server API for LabelerService service.
// All implementations must embed UnimplementedLabelerServiceServer
// for forward compatibility.
//
// LabelerService stamps Kubernetes manifests with platform labels.
type LabelerServiceServer interface {
	LabelStream(grpc.BidiStreamingServer[LabelStreamRequest, LabelStreamResponse]) error
	Label(grpc.ClientStreamingServer[LabelRequest, LabelResponse]) error
	mustEmbedUnimplementedLabelerServiceServer()
}

// UnimplementedLabelerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabelerServiceServer struct{}

func (UnimplementedLabelerServiceServer) LabelStream(grpc.BidiStreamingServer[LabelStreamRequest, LabelStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method LabelStream not implemented")
}
func (UnimplementedLabelerServiceServer) Label(grpc.ClientStreamingServer[LabelRequest, LabelResponse]) error {
	return status.Error(codes.Unimplemented, "method Label not implemented")
}
func (UnimplementedLabelerServiceServer) mustEmbedUnimplementedLabelerServiceServer() {}
func (UnimplementedLabelerServiceServer) testEmbeddedByValue()                        {}

// UnsafeLabelerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabelerServiceServer will
// result in compilation errors.
type UnsafeLabelerServiceServer interface {
	mustEmbedUnimplementedLabelerServiceServer()
}

func RegisterLabelerServiceServer(s grpc.ServiceRegistrar, srv LabelerServiceServer) {
	// If the following call panics, it indicates UnimplementedLabelerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LabelerService_ServiceDesc, srv)
}

func _LabelerService_LabelStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LabelerServiceServer).LabelStream(&grpc.GenericServerStream[LabelStreamRequest, LabelStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelerService_LabelStreamServer = grpc.BidiStreamingServer[LabelStreamRequest, LabelStreamResponse]

func _LabelerService_Label_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LabelerServiceServer).Label(&grpc.GenericServerStream[LabelRequest, LabelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LabelerService_LabelServer = grpc.ClientStreamingServer[LabelRequest, LabelResponse]

// LabelerService_ServiceDesc is the grpc.ServiceDesc for LabelerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LabelerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akrostolion.LabelerService",
	HandlerType: (*LabelerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LabelStream",
			Handler:       _LabelerService_LabelStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Label",
			Handler:       _LabelerService_Label_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "akrostolion/labeler.proto",
}
