// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: akrostolion/labeler.proto

package akrostolion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kubernetes manifest to label.
type LabelStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelStreamRequest) Reset() {
	*x = LabelStreamRequest{}
	mi := &file_akrostolion_labeler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelStreamRequest) ProtoMessage() {}

func (x *LabelStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akrostolion_labeler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelStreamRequest.ProtoReflect.Descriptor instead.
func (*LabelStreamRequest) Descriptor() ([]byte, []int) {
	return file_akrostolion_labeler_proto_rawDescGZIP(), []int{0}
}

func (x *LabelStreamRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Labeled Kubernetes manifest.
type LabelStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelStreamResponse) Reset() {
	*x = LabelStreamResponse{}
	mi := &file_akrostolion_labeler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelStreamResponse) ProtoMessage() {}

func (x *LabelStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akrostolion_labeler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelStreamResponse.ProtoReflect.Descriptor instead.
func (*LabelStreamResponse) Descriptor() ([]byte, []int) {
	return file_akrostolion_labeler_proto_rawDescGZIP(), []int{1}
}

func (x *LabelStreamResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Kubernetes manifest to label.
type LabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelRequest) Reset() {
	*x = LabelRequest{}
	mi := &file_akrostolion_labeler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelRequest) ProtoMessage() {}

func (x *LabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akrostolion_labeler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelRequest.ProtoReflect.Descriptor instead.
func (*LabelRequest) Descriptor() ([]byte, []int) {
	return file_akrostolion_labeler_proto_rawDescGZIP(), []int{2}
}

func (x *LabelRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Labeled Kubernetes manifest.
type LabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelResponse) Reset() {
	*x = LabelResponse{}
	mi := &file_akrostolion_labeler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelResponse) ProtoMessage() {}

func (x *LabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akrostolion_labeler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelResponse.ProtoReflect.Descriptor instead.
func (*LabelResponse) Descriptor() ([]byte, []int) {
	return file_akrostolion_labeler_proto_rawDescGZIP(), []int{3}
}

var File_akrostolion_labeler_proto protoreflect.FileDescriptor

const file_akrostolion_labeler_proto_rawDesc = "" +
	"\n" +
	"\x19akrostolion/labeler.proto\x12\vakrostolion\"0\n" +
	"\x12LabelStreamRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"1\n" +
	"\x13LabelStreamResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"*\n" +
	"\fLabelRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"\x0f\n" +
	"\rLabelResponse2\xa8\x01\n" +
	"\x0eLabelerService\x12T\n" +
	"\vLabelStream\x12\x1f.akrostolion.LabelStreamRequest\x1a .akrostolion.LabelStreamResponse(\x010\x01\x12@\n" +
	"\x05Label\x12\x19.akrostolion.LabelRequest\x1a\x1a.akrostolion.LabelResponse(\x01B#Z!github.com/katastroma/akrostolionb\x06proto3"

var (
	file_akrostolion_labeler_proto_rawDescOnce sync.Once
	file_akrostolion_labeler_proto_rawDescData []byte
)

func file_akrostolion_labeler_proto_rawDescGZIP() []byte {
	file_akrostolion_labeler_proto_rawDescOnce.Do(func() {
		file_akrostolion_labeler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_akrostolion_labeler_proto_rawDesc), len(file_akrostolion_labeler_proto_rawDesc)))
	})
	return file_akrostolion_labeler_proto_rawDescData
}

var file_akrostolion_labeler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_akrostolion_labeler_proto_goTypes = []any{
	(*LabelStreamRequest)(nil),  // 0: akrostolion.LabelStreamRequest
	(*LabelStreamResponse)(nil), // 1: akrostolion.LabelStreamResponse
	(*LabelRequest)(nil),        // 2: akrostolion.LabelRequest
	(*LabelResponse)(nil),       // 3: akrostolion.LabelResponse
}
var file_akrostolion_labeler_proto_depIdxs = []int32{
	0, // 0: akrostolion.LabelerService.LabelStream:input_type -> akrostolion.LabelStreamRequest
	2, // 1: akrostolion.LabelerService.Label:input_type -> akrostolion.LabelRequest
	1, // 2: akrostolion.LabelerService.LabelStream:output_type -> akrostolion.LabelStreamResponse
	3, // 3: akrostolion.LabelerService.Label:output_type -> akrostolion.LabelResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_akrostolion_labeler_proto_init() }
func file_akrostolion_labeler_proto_init() {
	if File_akrostolion_labeler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_akrostolion_labeler_proto_rawDesc), len(file_akrostolion_labeler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_akrostolion_labeler_proto_goTypes,
		DependencyIndexes: file_akrostolion_labeler_proto_depIdxs,
		MessageInfos:      file_akrostolion_labeler_proto_msgTypes,
	}.Build()
	File_akrostolion_labeler_proto = out.File
	file_akrostolion_labeler_proto_goTypes = nil
	file_akrostolion_labeler_proto_depIdxs = nil
}
